#!/bin/sh

# Check if codespell is installed
if ! command -v codespell > /dev/null; then
    echo "codespell is not installed. Please install it and try again."
    exit 1
fi

# Run codespell on staged files
# STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(py|js|md|txt|c|cpp|h|sh|yml|yaml|rs)$')
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

if [ -n "$STAGED_FILES" ]; then
    echo "Running codespell..."
    echo "$STAGED_FILES" | xargs codespell
    if [ $? -ne 0 ]; then
        echo "Spelling errors detected by codespell. Please fix them before committing."
        exit 1
    fi
else
    echo "No files to check with codespell."
fi

exit 0
